MAX_TRAIN=5000

default:
	echo love, or war?

generate:
	cp $(STEM)/$(STEM)-alltrain-examples.txt $(DEST)/alltrain-examples.txt
	cp $(STEM)/$(STEM)-test-examples.txt $(DEST)/test-examples.txt
	cp $(STEM)/$(STEM)-labels.txt $(DEST)/labels.txt
	cp $(STEM)/$(STEM)-corpus.graph $(DEST)/corpus.graph
	cp $(STEM)/$(STEM)-near.graph $(DEST)/near.graph
	cp $(STEM)/$(STEM)-cites.graph $(DEST)/cites.graph
